'BrauneDigital\RedirectBundle\Entity\Redirect':
    type: entity
    table: bd_redirect
    repositoryClass: 'BrauneDigital\RedirectBundle\Entity\RedirectRepository'
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        oldPath:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: old_path
        redirectPath:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: redirect_path
        statusCode:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: status_code
